### ISSUE TITLE
[flutter_foreground_service v. 0.1.1] -- Generates an error on iOS

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#238]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: iPhone 12 Pro Max - Simulator
 - OS: iOS 14.2

### Describe the bug

When using the new `carp_context_package` which uses the `activity_recognition` plugin which uses the `flutter_foreground_service` on iOS, I get a compile error:

```
/Users/bardram/dev/flutter-plugins/packages/activity_recognition_flutter/example/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'flutter_foreground_service' not found
@import flutter_foreground_service;
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### To Reproduce

Run the example in the `activity_recognition` plugin on iOS.

### Expected behavior

Even though `flutter_foreground_service` isn't relevant / used on iOS, it should not prevent building for iOS.

**Comment by thomasnilsson** [comment]
Fixed in v 0.2.0

**Comment by bardram** [comment]
I still get the same error in activity_recognition when using the new version 0.2.0:

```
    /Users/bardram/dev/flutter-plugins/packages/activity_recognition_flutter/example/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'flutter_foreground_service' not found
    @import flutter_foreground_service;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by thomasnilsson** [comment]
(Should be) Fixed in version 0.2.1

**Comment by thomasnilsson** [comment]
Can I close this @bardram ?

**Comment by bardram** [comment]
Yes - I can compile the AR demo to iOS now.
